if(NOT DEFINED CONTRACT_PYTHON OR NOT DEFINED SOURCE_DIR OR NOT DEFINED BUILD_DIR)
  message(FATAL_ERROR "CONTRACT_PYTHON, SOURCE_DIR, and BUILD_DIR are required")
endif()
set(operator "${SOURCE_DIR}/examples/DSP/dashboard/operator/fhss_dashboard_operator.py")
set(operator_build "${BUILD_DIR}")
set(output "${BUILD_DIR}/fhss-dashboard-operator-ctest")
if(INSTALLED_TREE)
  set(prefix "${BUILD_DIR}/fhss-dashboard-installed-ctest")
  file(REMOVE_RECURSE "${prefix}")
  execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}" --prefix "${prefix}"
                  RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "dashboard installed-tree install failed: ${result}")
  endif()
  set(operator "${prefix}/share/graphx/fhss-dashboard/operator/fhss_dashboard_operator.py")
  set(operator_build "${prefix}")
  set(output "${BUILD_DIR}/fhss-dashboard-installed-operator-ctest")
endif()
file(REMOVE_RECURSE "${output}")
execute_process(COMMAND "${CONTRACT_PYTHON}" "${operator}" exercise --phase 1
                        --build-dir "${operator_build}" --output-dir "${output}"
                RESULT_VARIABLE exercise_result)
if(NOT exercise_result EQUAL 0)
  message(FATAL_ERROR "dashboard operator exercise failed: ${exercise_result}")
endif()
execute_process(COMMAND "${CONTRACT_PYTHON}" "${operator}" verify --output-dir "${output}"
                RESULT_VARIABLE verify_result)
if(NOT verify_result EQUAL 0)
  message(FATAL_ERROR "dashboard operator verify failed: ${verify_result}")
endif()
